'''
This script retrieves code snippets related to a specific entity's relationships,
based on reports generated by ENRE-Java and the relation_analyzer.py script.
'''
import json
import os
import argparse
import sys

# Add tree-sitter directory to path
current_dir = os.path.dirname(os.path.abspath(__file__))
tree_sitter_dir = os.path.join(os.path.dirname(current_dir), 'tree-sitter')
if tree_sitter_dir not in sys.path:
    sys.path.append(tree_sitter_dir)

try:
    from tree_Sitter_parse import setup_java_parser, get_minimal_logical_block
    HAS_TREE_SITTER = True
except ImportError:
    print("Warning: Could not import tree_Sitter_parse. Logic for minimal block will fallback to default.")
    HAS_TREE_SITTER = False

JAVA_PARSER = None

def get_java_parser():
    global JAVA_PARSER
    if JAVA_PARSER is None and HAS_TREE_SITTER:
        try:
            JAVA_PARSER = setup_java_parser()
        except Exception as e:
            print(f"Error setting up Java parser: {e}")
    return JAVA_PARSER

def get_smart_snippet(file_path, start_line, default_context=5):
    """
    Tries to get the minimal logical block using tree-sitter.
    Falls back to context window if fails.
    """
    parser = get_java_parser()
    # print(f"parser: {parser}")
    if parser and os.path.exists(file_path):
        try:
            blk_start, blk_end = get_minimal_logical_block(parser, file_path, start_line)
            # if(blk_start!=start_line):
            #     print(f"blk_start: {blk_start}, start_line: {start_line}, blk_end: {blk_end}")
            #     input("Press Enter to continue...")
            # Use the exact block range
            # We must pass context_lines large enough because get_code_snippet uses it as a limit (start + context - 1)
            block_len = blk_end - blk_start + 1
            return get_code_snippet(file_path, blk_start, end_line=blk_end, context_lines=block_len)
        except Exception as e:
            # print(f"Tree-sitter parsing failed for {file_path}:{start_line}: {e}")
            pass
            
    return get_code_snippet(file_path, start_line, context_lines=default_context)

def get_code_snippet(file_path, start_line, end_line=None, context_lines=5):
    """
    Extracts a snippet of code from a file.

    Args:
        file_path (str): The absolute path to the source code file.
        start_line (int): The starting line number (1-indexed).
        end_line (int, optional): The ending line number. If None, extracts a context window around start_line.
        context_lines (int): The number of lines to include before and after the target line(s).

    Returns:
        str: The extracted code snippet, or an error message if the file cannot be read.
    """
    if not os.path.exists(file_path):
        return f"Error: Source file not found at {file_path}"

    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()
    except UnicodeDecodeError:
        print(f"Warning: Failed to decode '{file_path}' with UTF-8. Retrying with 'latin-1' encoding.")
        try:
            with open(file_path, 'r', encoding='latin-1') as f:
                lines = f.readlines()
        except Exception as e:
            print(f"Error reading file '{file_path}' with fallback encoding 'latin-1': {e}")
            return None  
    except Exception as e:
        return f"Error reading file {file_path}: {e}"

    # Adjust for 0-based indexing
    start_idx = start_line - 1

    if end_line is not None:
        # Extract a specific block (e.g., method definition's first few lines)
        end_idx = min(end_line - 1, start_idx + context_lines -1, len(lines) - 1)
    else:
        # Extract a context window around a single line
        start_idx = max(0, start_line - 1 - context_lines)
        end_idx = min(len(lines) - 1, start_line - 1 + context_lines)

    snippet_lines = lines[start_idx : end_idx + 1]
    return "".join(snippet_lines)

def retrieve_code_context(entity_relations: dict, enre_report_path: str, project_root: str, output_path: str | None = None) -> dict | None:
    """
    Main function to retrieve code context for a single entity's relations.
    
    Args:
        entity_relations (dict): A dictionary representing a single entity's relations (from relation_analyzer).
        enre_report_path (str): Path to the full ENRE-Java JSON output file.
        project_root (str): The root directory of the analyzed Java project.
        output_path (str, optional): If provided, saves the augmented results to this file path. Defaults to None.

    Returns:
        dict: The augmented entity relations dictionary with code snippets, or None on error.
    """
    # 1. Load the full ENRE report and create lookup maps
    try:
        with open(enre_report_path, 'r', encoding='utf-8') as f:
            enre_data = json.load(f)
    except UnicodeDecodeError:
        print(f"Warning: Failed to decode '{enre_report_path}' with UTF-8. Retrying with 'latin-1' encoding.")
        try:
            with open(enre_report_path, 'r', encoding='latin-1') as f:
                enre_data = json.load(f)
        except Exception as e:
            print(f"Error reading file '{enre_report_path}' with fallback encoding 'latin-1': {e}")
            return None
    except (IOError, json.JSONDecodeError) as e:
        print(f"Error reading or parsing ENRE report '{enre_report_path}': {e}")
        return None

    enre_node_map = {var['qualifiedName']: var for var in enre_data.get('variables', [])}
    
    parent_id_to_methods_map = {}
    for var in enre_data.get('variables', []):
        if var.get('category') == 'Method':
            parent_id = var.get('parentId')
            if parent_id is not None:
                if parent_id not in parent_id_to_methods_map:
                    parent_id_to_methods_map[parent_id] = []
                parent_id_to_methods_map[parent_id].append(var)

    # 2. Process the entity based on its category
    category = entity_relations.get('category')

    if category == 'Method':
        # Process 'calls' relationships
        if 'calls' in entity_relations:
            for call_info in entity_relations['calls']:
                called_qname = call_info.get('qualifiedName')
                target_node = enre_node_map.get(called_qname)
                
                if target_node:
                    file_path = os.path.join(project_root, target_node.get('File', ''))
                    location = target_node.get('location', {})
                    start_line = location.get('startLine')
                    end_line = location.get('endLine')
                    
                    if start_line:
                        snippet = get_code_snippet(file_path, start_line, end_line, context_lines=5)
                        call_info['code_snippet'] = snippet
                        call_info['method_location'] = {'startLine': start_line, 'endLine': end_line}

        # Process 'called_by' relationships
        if 'called_by' in entity_relations:
            for caller_info in entity_relations['called_by']:
                file_path = os.path.join(project_root, caller_info.get('File', ''))
                location = caller_info.get('location', {})
                start_line = location.get('startLine')

                if start_line:
                    snippet = get_smart_snippet(file_path, start_line, default_context=5)
                    caller_info['code_snippet'] = snippet

    elif category == 'Class':
        # Process 'instantiated_in'
        for info in entity_relations.get('instantiated_in', []):
            file_path = os.path.join(project_root, info.get('File', ''))
            start_line = info.get('startLine')
            if start_line:
                snippet = get_smart_snippet(file_path, start_line, default_context=5)
                info['code_snippet'] = snippet

        # Process 'inherits_from' to get parent's methods
        for info in entity_relations.get('inherits_from', []):
            parent_id = info.get('id')
            methods = parent_id_to_methods_map.get(parent_id, [])
            info['contained_methods_snippets'] = []
            for method_data in methods:
                method_file_path = os.path.join(project_root, method_data.get('File', ''))
                method_location = method_data.get('location', {})
                method_start_line = method_location.get('startLine')
                if method_start_line:
                    snippet = get_code_snippet(method_file_path, method_start_line, context_lines=3)
                    info['contained_methods_snippets'].append({
                        'qualifiedName': method_data.get('qualifiedName'),
                        'code_snippet': snippet
                    })
        
        # Process 'implements' to get interface's methods
        for info in entity_relations.get('implements', []):
            interface_id = info.get('id')
            methods = parent_id_to_methods_map.get(interface_id, [])
            info['contained_methods_snippets'] = []
            for method_data in methods:
                method_file_path = os.path.join(project_root, method_data.get('File', ''))
                method_location = method_data.get('location', {})
                method_start_line = method_location.get('startLine')
                if method_start_line:
                    snippet = get_code_snippet(method_file_path, method_start_line, context_lines=3) #Test Fix
                    info['contained_methods_snippets'].append({
                        'qualifiedName': method_data.get('qualifiedName'),
                        'code_snippet': snippet
                    })
    
    elif category == 'Interface':
        # Process 'inherits_from' to get parent interface's methods
        for info in entity_relations.get('inherits_from', []):
            parent_id = info.get('id')
            methods = parent_id_to_methods_map.get(parent_id, [])
            info['contained_methods_snippets'] = []
            for method_data in methods:
                method_file_path = os.path.join(project_root, method_data.get('File', ''))
                method_location = method_data.get('location', {})
                method_start_line = method_location.get('startLine')
                if method_start_line:
                    snippet = get_code_snippet(method_file_path, method_start_line, context_lines=3)
                    info['contained_methods_snippets'].append({
                        'qualifiedName': method_data.get('qualifiedName'),
                        'code_snippet': snippet
                    })

    # 4. Save the augmented results if an output path is provided
    if output_path:
        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump([entity_relations], f, indent=4)
            print(f"Code context retrieval complete. Results saved to '{os.path.abspath(output_path)}'")
        except IOError as e:
            print(f"Error writing to output file '{output_path}': {e}")
        
    return entity_relations

def main():
    parser = argparse.ArgumentParser(description='Retrieve code snippets for entity relationships from ENRE reports.')
    parser.add_argument('--relation_report_file', required=True, help='Path to the JSON file containing the specific entity relationship report.')
    parser.add_argument('--enre_report_file', required=True, help='Path to the full ENRE-Java JSON output file.')
    parser.add_argument('--project_root', required=True, help='The root directory of the analyzed Java project.')
    parser.add_argument('--output_file', default='code_context_report.json', help='Path to save the output JSON file with code snippets.')
    
    args = parser.parse_args()

    # Read the input relation report
    try:
        with open(args.relation_report_file, 'r', encoding='utf-8') as f:
            relation_data = json.load(f)
        if not relation_data or not isinstance(relation_data, list):
            print("Error: Relation report is empty or not in the expected list format.")
            return
        entity_relations = relation_data[0]
    except (IOError, json.JSONDecodeError, IndexError) as e:
        print(f"Error reading or parsing relation report '{args.relation_report_file}': {e}")
        return

    # Call the main function, which will now handle the file output internally
    retrieve_code_context(
        entity_relations=entity_relations,
        enre_report_path=args.enre_report_file,
        project_root=args.project_root,
        output_path=args.output_file
    )

if __name__ == '__main__':
    main()
