'''
This script analyzes a JSON report generated by ENRE-Java to extract and summarize
relationships (Inherit, Implement, Call) between Classes, Interfaces, and Methods.
'''
import json
import os
import argparse

def analyze_java_enre_report(report_path, target_qualified_name=None, enre_data=None):
    """
    Parses a Java ENRE report to analyze relationships. Can be passed a file path
    or a pre-loaded data dictionary.
    """
    # If data is not passed directly, load it from the file.
    if enre_data:
        data = enre_data
    elif report_path and os.path.exists(report_path):
        try:
            with open(report_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
        except UnicodeDecodeError:
            print(f"Warning: Failed to decode '{report_path}' with UTF-8. Retrying with 'latin-1' encoding.")
            try:
                with open(report_path, 'r', encoding='latin-1') as f:
                    data = json.load(f)
            except Exception as e:
                print(f"Error reading file '{report_path}' with fallback encoding 'latin-1': {e}")
                return None
        except json.JSONDecodeError as e:
            print(f"Error decoding JSON from '{report_path}': {e}")
            return None
    else:
        print(f"Error: Report file not found at '{report_path}' and no data provided.")
        return None

    variables = data.get('variables', [])
    cells = data.get('cells', [])

    # 1. Filter for relevant nodes (Interface, Class, Method) and map their IDs to their data.
    node_map = {
        var['id']: var for var in variables
        if var.get('category') in ['Interface', 'Class', 'Method']
    }

    # Pre-computation for Class instantiations and contained methods
    class_qname_to_id = {var['qualifiedName']: var['id'] for var in variables if var.get('category') == 'Class'}
    
    class_to_methods = {}
    for var in variables:
        if var.get('category') == 'Method':
            parent_id = var.get('parentId')
            if parent_id is not None:
                if parent_id not in class_to_methods:
                    class_to_methods[parent_id] = []
                class_to_methods[parent_id].append({
                    'qualifiedName': var.get('qualifiedName'),
                    'location': var.get('location')
                })

    class_instantiations = {}
    for var in variables:
        if var.get('category') == 'Variable':
            raw_type = var.get('rawType')
            if raw_type in class_qname_to_id:
                class_id = class_qname_to_id[raw_type]
                if class_id not in class_instantiations:
                    class_instantiations[class_id] = []
                class_instantiations[class_id].append({
                    'File': var.get('File'),
                    'startLine': var.get('location', {}).get('startLine')
                })

    # 2. Initialize structures based on entity category.
    analysis_results = {}
    for node_id, node_info in node_map.items():
        category = node_info.get('category')
        result = {
            'id': node_id,
            'qualifiedName': node_info.get('qualifiedName', 'N/A'),
            'category': category,
            'File': node_info.get('File', 'N/A'),
        }
        if category == 'Method':
            result['calls'] = []
            result['called_by'] = []
        elif category == 'Class':
            result['inherits_from'] = []
            result['subclasses'] = []
            result['implements'] = []
            result['instantiated_in'] = class_instantiations.get(node_id, [])
            result['contains_methods'] = class_to_methods.get(node_id, [])
        elif category == 'Interface':
            result['inherits_from'] = []  # Interfaces extending this one (via Inherit)
            result['implemented_by'] = [] # Classes implementing this one
        
        analysis_results[node_id] = result

    # 3. Process all relationships from the 'cells' data.
    for cell in cells:
        src_id = cell.get('src')
        dest_id = cell.get('dest')
        values = cell.get('values', {})
        
        # In Java ENRE output, 'loc' is inside 'values'
        location = values.get('loc', {})

        # Ensure both source and destination are nodes we are tracking.
        if src_id not in node_map or dest_id not in node_map:
            continue

        src_node_info = node_map[src_id]
        dest_node_info = node_map[dest_id]

        # A. Handle 'Call' relationships (Method -> Method)
        if 'Call' in values:
            if src_node_info.get('category') == 'Method' and dest_node_info.get('category') == 'Method':
                analysis_results[src_id]['calls'].append({
                    'id': dest_id,
                    'qualifiedName': dest_node_info.get('qualifiedName', 'N/A'),
                    'File': dest_node_info.get('File', 'N/A'),
                    'location': location
                })
                analysis_results[dest_id]['called_by'].append({
                    'id': src_id,
                    'qualifiedName': src_node_info.get('qualifiedName', 'N/A'),
                    'File': src_node_info.get('File', 'N/A'),
                    'location': location
                })

        # B. Handle 'Inherit' relationships (Class -> Class/Interface)
        if 'Inherit' in values:
            if src_node_info.get('category') == 'Class' and dest_node_info.get('category') in ['Class', 'Interface']:
                analysis_results[src_id]['inherits_from'].append({
                    'id': dest_id,
                    'qualifiedName': dest_node_info.get('qualifiedName', 'N/A'),
                    'File': dest_node_info.get('File', 'N/A')
                })
                analysis_results[dest_id]['subclasses'].append({
                    'id': src_id,
                    'qualifiedName': src_node_info.get('qualifiedName', 'N/A'),
                    'File': src_node_info.get('File', 'N/A')
                })

        # C. Handle 'Implement' relationships (Class -> Interface)
        if 'Implement' in values:
            if src_node_info.get('category') == 'Class' and dest_node_info.get('category') == 'Interface':
                analysis_results[src_id]['implements'].append({
                    'id': dest_id,
                    'qualifiedName': dest_node_info.get('qualifiedName', 'N/A'),
                    'File': dest_node_info.get('File', 'N/A')
                })
                analysis_results[dest_id]['implemented_by'].append({
                    'id': src_id,
                    'qualifiedName': src_node_info.get('qualifiedName', 'N/A'),
                    'File': src_node_info.get('File', 'N/A')
                })

    # If a specific qualifiedName is targeted, filter the results.
    if target_qualified_name:
        target_id = None
        for node_id, node_info in node_map.items():
            if node_info.get('qualifiedName') == target_qualified_name:
                target_id = node_id
                break
        
        if target_id and target_id in analysis_results:
            # Keep only the result for the target entity
            analysis_results = {target_id: analysis_results[target_id]}
            print(f"Found entity: {target_qualified_name}. Analyzing its relationships.")
        else:
            print(f"Warning: Entity with qualifiedName '{target_qualified_name}' not found in the report.")
            return [] # Return empty list if not found

    # 4. Finalize the results: sort for consistency and calculate totals.
    for result in analysis_results.values():
        # Sort lists for consistent output, using .get() to avoid errors on missing keys
        if 'calls' in result:
            result['calls'] = sorted(result['calls'], key=lambda x: (x['qualifiedName'], x.get('location', {}).get('startLine', 0)))
        if 'called_by' in result:
            result['called_by'] = sorted(result['called_by'], key=lambda x: (x['qualifiedName'], x.get('location', {}).get('startLine', 0)))
        if 'inherits_from' in result:
            result['inherits_from'] = sorted(result['inherits_from'], key=lambda x: x['qualifiedName'])
        if 'subclasses' in result:
            result['subclasses'] = sorted(result['subclasses'], key=lambda x: x['qualifiedName'])
        if 'implements' in result:
            result['implements'] = sorted(result['implements'], key=lambda x: x['qualifiedName'])
        if 'implemented_by' in result:
            result['implemented_by'] = sorted(result['implemented_by'], key=lambda x: x['qualifiedName'])
        if 'instantiated_in' in result:
            result['instantiated_in'] = sorted(result['instantiated_in'], key=lambda x: (x.get('File', ''), x.get('startLine', 0)))
        if 'contains_methods' in result:
            result['contains_methods'] = sorted(result['contains_methods'], key=lambda x: x.get('location', {}).get('startLine', 0))

        # Calculate total relations safely
        total_relations = 0
        relation_keys = ['calls', 'called_by', 'inherits_from', 'subclasses', 'implements', 'implemented_by']
        for key in relation_keys:
            total_relations += len(result.get(key, []))
        result['total_relations'] = total_relations

    # Convert dict to list for final output
    final_results_list = list(analysis_results.values())
    
    # Sort the final list by total relations in descending order
    sorted_results = sorted(final_results_list, key=lambda item: item['total_relations'], reverse=True)

    return sorted_results

def main():
    """
    Main function to run the analysis and save the report to a JSON file.
    """
    parser = argparse.ArgumentParser(description='Analyze Java ENRE reports for specific relationships.')
    parser.add_argument('input_file', help='Path to the ENRE JSON report file.')
    parser.add_argument('-o', '--output_file', default='java_analysis_report.json', help='Path to save the analysis output JSON file. Defaults to "java_analysis_report.json" in the current directory.')
    parser.add_argument('-q', '--qualified_name', help='Optional: The qualifiedName of a specific entity to analyze.')
    
    args = parser.parse_args()

    results = analyze_java_enre_report(args.input_file, args.qualified_name)

    if results:
        # Save the sorted results to the specified output file
        try:
            with open(args.output_file, 'w', encoding='utf-8') as f:
                json.dump(results, f, indent=4)
            print(f"Analysis complete. Results saved to '{os.path.abspath(args.output_file)}'")
        except IOError as e:
            print(f"Error writing to output file '{args.output_file}': {e}")

if __name__ == '__main__':
    main()
