'''
This script retrieves code snippets related to a specific entity's relationships,
based on reports generated by ENRE-Python and py_utils/relation_analyzer.py.
'''
import json
import os
import argparse


def get_code_snippet(file_path, start_line, end_line=None, context_lines=5):
    if not os.path.exists(file_path):
        return f"Error: Source file not found at {file_path}"

    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()
    except UnicodeDecodeError:
        print(f"Warning: Failed to decode '{file_path}' with UTF-8. Retrying with 'latin-1' encoding.")
        try:
            with open(file_path, 'r', encoding='latin-1') as f:
                lines = f.readlines()
        except Exception as e:
            print(f"Error reading file '{file_path}' with fallback encoding 'latin-1': {e}")
            return None
    except Exception as e:
        return f"Error reading file {file_path}: {e}"

    if not isinstance(start_line, int) or start_line <= 0:
        return None

    start_idx = start_line - 1
    if end_line is not None and isinstance(end_line, int) and end_line >= start_line:
        end_idx = min(end_line - 1, start_idx + context_lines - 1, len(lines) - 1)
    else:
        start_idx = max(0, start_line - 1 - context_lines)
        end_idx = min(len(lines) - 1, start_line - 1 + context_lines)

    snippet_lines = lines[start_idx : end_idx + 1]
    return "".join(snippet_lines)


def retrieve_code_context(entity_relations: dict, enre_report_path: str, project_root: str, output_path: str | None = None) -> dict | None:
    try:
        with open(enre_report_path, 'r', encoding='utf-8') as f:
            enre_data = json.load(f)
    except UnicodeDecodeError:
        print(f"Warning: Failed to decode '{enre_report_path}' with UTF-8. Retrying with 'latin-1' encoding.")
        try:
            with open(enre_report_path, 'r', encoding='latin-1') as f:
                enre_data = json.load(f)
        except Exception as e:
            print(f"Error reading file '{enre_report_path}' with fallback encoding 'latin-1': {e}")
            return None
    except (IOError, json.JSONDecodeError) as e:
        print(f"Error reading or parsing ENRE report '{enre_report_path}': {e}")
        return None

    enre_node_map = {var['qualifiedName']: var for var in enre_data.get('variables', []) if var.get('qualifiedName')}
    id_node_map = {var['id']: var for var in enre_data.get('variables', []) if 'id' in var}

    class_qname_to_id = {
        var.get('qualifiedName'): var.get('id')
        for var in enre_data.get('variables', [])
        if var.get('category') == 'Class' and var.get('qualifiedName') and var.get('id') is not None
    }

    def find_enclosing_class_id(function_qname: str) -> int | None:
        if not function_qname:
            return None
        best = None
        for class_qname, class_id in class_qname_to_id.items():
            if function_qname.startswith(class_qname + "."):
                if best is None or len(class_qname) > len(best[0]):
                    best = (class_qname, class_id)
        return best[1] if best else None

    parent_id_to_functions_map = {}
    for var in enre_data.get('variables', []):
        if var.get('category') != 'Function':
            continue
        parent_id = var.get('parentId')
        if parent_id is None:
            parent_id = find_enclosing_class_id(var.get('qualifiedName', ''))
        if parent_id is None:
            continue
        parent_id_to_functions_map.setdefault(parent_id, []).append(var)

    category = entity_relations.get('category')

    if category == 'Function':
        if 'calls' in entity_relations:
            for call_info in entity_relations['calls']:
                called_qname = call_info.get('qualifiedName')
                target_node = enre_node_map.get(called_qname)
                if target_node:
                    file_path = os.path.join(project_root, target_node.get('File', ''))
                    location = target_node.get('location', {})
                    start_line = location.get('startLine')
                    end_line = location.get('endLine')
                    if start_line:
                        snippet = get_code_snippet(file_path, start_line, end_line, context_lines=5)
                        call_info['code_snippet'] = snippet
                        call_info['target_location'] = {'startLine': start_line, 'endLine': end_line}

        if 'called_by' in entity_relations:
            for caller_info in entity_relations['called_by']:
                file_path = os.path.join(project_root, caller_info.get('File', ''))
                location = caller_info.get('location', {})
                start_line = location.get('startLine')
                if start_line:
                    snippet = get_code_snippet(file_path, start_line, context_lines=5)
                    caller_info['code_snippet'] = snippet

    elif category == 'Class':
        for info in entity_relations.get('instantiated_in', []):
            file_path = os.path.join(project_root, info.get('File', ''))
            start_line = info.get('startLine') or info.get('location', {}).get('startLine')
            if start_line:
                snippet = get_code_snippet(file_path, start_line, context_lines=5)
                info['code_snippet'] = snippet

        for info in entity_relations.get('inherits_from', []):
            parent_id = info.get('id')
            methods = parent_id_to_functions_map.get(parent_id, [])
            info['contained_functions_snippets'] = []
            for method_data in methods:
                method_file_path = os.path.join(project_root, method_data.get('File', ''))
                method_location = method_data.get('location', {})
                method_start_line = method_location.get('startLine')
                method_end_line = method_location.get('endLine')
                if method_start_line:
                    snippet = get_code_snippet(method_file_path, method_start_line, method_end_line, context_lines=3)
                    info['contained_functions_snippets'].append({
                        'qualifiedName': method_data.get('qualifiedName'),
                        'code_snippet': snippet
                    })

    elif category in {'Module', 'Package'}:
        for info in entity_relations.get('imports', []):
            imported_qname = info.get('qualifiedName')
            target_node = enre_node_map.get(imported_qname)
            if target_node:
                file_path = os.path.join(project_root, target_node.get('File', ''))
                location = target_node.get('location', {})
                start_line = location.get('startLine')
                end_line = location.get('endLine')
                if start_line:
                    info['code_snippet'] = get_code_snippet(file_path, start_line, end_line=end_line, context_lines=5)

        for info in entity_relations.get('contains', []):
            target_id = info.get('id')
            target_node = id_node_map.get(target_id)
            if target_node:
                file_path = os.path.join(project_root, target_node.get('File', ''))
                location = target_node.get('location', {})
                start_line = location.get('startLine')
                end_line = location.get('endLine')
                if start_line:
                    info['code_snippet'] = get_code_snippet(file_path, start_line, end_line=end_line, context_lines=3)

    if output_path:
        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump([entity_relations], f, indent=4)
            print(f"Code context retrieval complete. Results saved to '{os.path.abspath(output_path)}'")
        except IOError as e:
            print(f"Error writing to output file '{output_path}': {e}")

    return entity_relations


def main():
    parser = argparse.ArgumentParser(description='Retrieve code snippets for Python entity relationships from ENRE reports.')
    parser.add_argument('--relation_report_file', required=True, help='Path to the JSON file containing the specific entity relationship report.')
    parser.add_argument('--enre_report_file', required=True, help='Path to the full ENRE-Python JSON output file.')
    parser.add_argument('--project_root', required=True, help='The root directory of the analyzed Python project.')
    parser.add_argument('--output_file', default='python_code_context_report.json', help='Path to save the output JSON file with code snippets.')

    args = parser.parse_args()

    try:
        with open(args.relation_report_file, 'r', encoding='utf-8') as f:
            relation_data = json.load(f)
        if not relation_data or not isinstance(relation_data, list):
            print("Error: Relation report is empty or not in the expected list format.")
            return
        entity_relations = relation_data[0]
    except (IOError, json.JSONDecodeError, IndexError) as e:
        print(f"Error reading or parsing relation report '{args.relation_report_file}': {e}")
        return

    retrieve_code_context(
        entity_relations=entity_relations,
        enre_report_path=args.enre_report_file,
        project_root=args.project_root,
        output_path=args.output_file
    )


if __name__ == '__main__':
    main()
