'''
This script analyzes a JSON report generated by ENRE-Python to extract and summarize
one-hop relationships around Function, Class, Module, and Package entities.
'''
import json
import os
import argparse


def _extract_kind(values: dict) -> str | None:
    if not isinstance(values, dict):
        return None
    kind = values.get('kind')
    if isinstance(kind, str) and kind:
        return kind
    for legacy in ('Call', 'Inherit', 'Import', 'Contain'):
        if legacy in values:
            return legacy
    return None


def _extract_location(cell: dict, values: dict) -> dict:
    loc = values.get('loc')
    if isinstance(loc, dict) and loc:
        return loc
    loc = cell.get('location')
    if isinstance(loc, dict) and loc:
        return loc
    return {}


def analyze_python_enre_report(report_path, target_qualified_name=None, enre_data=None):
    """
    Parses a Python ENRE report to analyze one-hop relationships.
    Can be passed a file path or a pre-loaded data dictionary.
    """
    if enre_data:
        data = enre_data
    elif report_path and os.path.exists(report_path):
        try:
            with open(report_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
        except UnicodeDecodeError:
            print(f"Warning: Failed to decode '{report_path}' with UTF-8. Retrying with 'latin-1' encoding.")
            try:
                with open(report_path, 'r', encoding='latin-1') as f:
                    data = json.load(f)
            except Exception as e:
                print(f"Error reading file '{report_path}' with fallback encoding 'latin-1': {e}")
                return None
        except json.JSONDecodeError as e:
            print(f"Error decoding JSON from '{report_path}': {e}")
            return None
    else:
        print(f"Error: Report file not found at '{report_path}' and no data provided.")
        return None

    variables = data.get('variables', [])
    cells = data.get('cells', [])

    tracked_categories = {'Function', 'Class', 'Module', 'Package'}
    node_map = {
        var['id']: var for var in variables
        if var.get('category') in tracked_categories
    }

    id_to_var = {var.get('id'): var for var in variables}

    class_qname_to_id = {
        var.get('qualifiedName'): var.get('id')
        for var in variables
        if var.get('category') == 'Class' and var.get('qualifiedName') and var.get('id') is not None
    }

    def find_enclosing_class_id(function_qname: str) -> int | None:
        if not function_qname:
            return None
        best = None
        for class_qname, class_id in class_qname_to_id.items():
            if function_qname.startswith(class_qname + "."):
                if best is None or len(class_qname) > len(best[0]):
                    best = (class_qname, class_id)
        return best[1] if best else None

    class_to_functions = {}
    for var in variables:
        if var.get('category') != 'Function':
            continue
        parent_id = var.get('parentId')
        if parent_id is None:
            parent_id = find_enclosing_class_id(var.get('qualifiedName', ''))
        if parent_id is None:
            continue
        class_to_functions.setdefault(parent_id, []).append({
            'qualifiedName': var.get('qualifiedName'),
            'location': var.get('location'),
            'File': var.get('File'),
            'id': var.get('id'),
        })

    class_instantiations = {}
    for cell in cells:
        src_id = cell.get('src')
        dest_id = cell.get('dest')
        values = cell.get('values', {})
        kind = _extract_kind(values)
        if kind != 'Call':
            continue

        dest_var = id_to_var.get(dest_id, {})
        dest_category = dest_var.get('category')
        location = _extract_location(cell, values)

        class_id = None
        if dest_category == 'Class':
            class_id = dest_id
        elif dest_category == 'Function':
            dest_qname = dest_var.get('qualifiedName', '') or ''
            dest_name = dest_qname.rsplit('.', 1)[-1] if dest_qname else ''
            if dest_name == '__init__':
                parent_id = dest_var.get('parentId')
                if parent_id is None:
                    parent_id = find_enclosing_class_id(dest_qname)
                parent_var = id_to_var.get(parent_id, {}) if parent_id is not None else {}
                if parent_var.get('category') == 'Class':
                    class_id = parent_id

        if class_id is None:
            continue

        src_var = id_to_var.get(src_id, {})
        class_instantiations.setdefault(class_id, []).append({
            'id': src_id,
            'qualifiedName': src_var.get('qualifiedName', 'N/A'),
            'File': src_var.get('File', 'N/A'),
            'location': location,
            'startLine': location.get('startLine'),
        })

    analysis_results = {}
    for node_id, node_info in node_map.items():
        category = node_info.get('category')
        result = {
            'id': node_id,
            'qualifiedName': node_info.get('qualifiedName', 'N/A'),
            'category': category,
            'File': node_info.get('File', 'N/A'),
        }
        if category == 'Function':
            result['calls'] = []
            result['called_by'] = []
        elif category == 'Class':
            result['inherits_from'] = []
            result['subclasses'] = []
            result['instantiated_in'] = class_instantiations.get(node_id, [])
            result['contains_functions'] = class_to_functions.get(node_id, [])
        elif category in {'Module', 'Package'}:
            result['contains'] = []
            result['imports'] = []
            result['imported_by'] = []
        analysis_results[node_id] = result

    for cell in cells:
        src_id = cell.get('src')
        dest_id = cell.get('dest')
        values = cell.get('values', {})
        kind = _extract_kind(values)
        location = _extract_location(cell, values)

        if src_id not in node_map or dest_id not in node_map:
            continue

        src_node_info = node_map[src_id]
        dest_node_info = node_map[dest_id]
        src_category = src_node_info.get('category')
        dest_category = dest_node_info.get('category')

        if kind == 'Call' and src_category == 'Function':
            analysis_results[src_id]['calls'].append({
                'id': dest_id,
                'qualifiedName': dest_node_info.get('qualifiedName', 'N/A'),
                'category': dest_category,
                'File': dest_node_info.get('File', 'N/A'),
                'location': location,
            })
            if dest_category == 'Function':
                analysis_results[dest_id]['called_by'].append({
                    'id': src_id,
                    'qualifiedName': src_node_info.get('qualifiedName', 'N/A'),
                    'File': src_node_info.get('File', 'N/A'),
                    'location': location,
                })

        if kind == 'Inherit' and src_category == 'Class' and dest_category == 'Class':
            analysis_results[src_id]['inherits_from'].append({
                'id': dest_id,
                'qualifiedName': dest_node_info.get('qualifiedName', 'N/A'),
                'File': dest_node_info.get('File', 'N/A'),
            })
            analysis_results[dest_id]['subclasses'].append({
                'id': src_id,
                'qualifiedName': src_node_info.get('qualifiedName', 'N/A'),
                'File': src_node_info.get('File', 'N/A'),
            })

        if kind == 'Contain' and src_category in {'Module', 'Package'} and dest_category in {'Module', 'Package'}:
            analysis_results[src_id]['contains'].append({
                'id': dest_id,
                'qualifiedName': dest_node_info.get('qualifiedName', 'N/A'),
                'category': dest_category,
                'File': dest_node_info.get('File', 'N/A'),
            })

        if kind == 'Import' and src_category == 'Module' and dest_category == 'Module':
            analysis_results[src_id]['imports'].append({
                'id': dest_id,
                'qualifiedName': dest_node_info.get('qualifiedName', 'N/A'),
                'File': dest_node_info.get('File', 'N/A'),
                'location': location,
            })
            analysis_results[dest_id]['imported_by'].append({
                'id': src_id,
                'qualifiedName': src_node_info.get('qualifiedName', 'N/A'),
                'File': src_node_info.get('File', 'N/A'),
                'location': location,
            })

    if target_qualified_name:
        target_id = None
        for node_id, node_info in node_map.items():
            if node_info.get('qualifiedName') == target_qualified_name:
                target_id = node_id
                break

        if target_id and target_id in analysis_results:
            analysis_results = {target_id: analysis_results[target_id]}
            print(f"Found entity: {target_qualified_name}. Analyzing its relationships.")
        else:
            print(f"Warning: Entity with qualifiedName '{target_qualified_name}' not found in the report.")
            return []

    for result in analysis_results.values():
        if 'calls' in result:
            result['calls'] = sorted(result['calls'], key=lambda x: (x.get('qualifiedName', ''), x.get('location', {}).get('startLine', 0)))
        if 'called_by' in result:
            result['called_by'] = sorted(result['called_by'], key=lambda x: (x.get('qualifiedName', ''), x.get('location', {}).get('startLine', 0)))
        if 'inherits_from' in result:
            result['inherits_from'] = sorted(result['inherits_from'], key=lambda x: x.get('qualifiedName', ''))
        if 'subclasses' in result:
            result['subclasses'] = sorted(result['subclasses'], key=lambda x: x.get('qualifiedName', ''))
        if 'instantiated_in' in result:
            result['instantiated_in'] = sorted(result['instantiated_in'], key=lambda x: (x.get('File', ''), x.get('startLine', 0) or 0))
        if 'contains_functions' in result:
            result['contains_functions'] = sorted(result['contains_functions'], key=lambda x: x.get('location', {}).get('startLine', 0))
        if 'contains' in result:
            result['contains'] = sorted(result['contains'], key=lambda x: (x.get('category', ''), x.get('qualifiedName', '')))
        if 'imports' in result:
            result['imports'] = sorted(result['imports'], key=lambda x: (x.get('qualifiedName', ''), x.get('location', {}).get('startLine', 0)))
        if 'imported_by' in result:
            result['imported_by'] = sorted(result['imported_by'], key=lambda x: (x.get('qualifiedName', ''), x.get('location', {}).get('startLine', 0)))

        relation_keys = ['calls', 'called_by', 'inherits_from', 'subclasses', 'instantiated_in', 'contains', 'imports', 'imported_by']
        total_relations = 0
        for key in relation_keys:
            total_relations += len(result.get(key, []))
        result['total_relations'] = total_relations

    final_results_list = list(analysis_results.values())
    sorted_results = sorted(final_results_list, key=lambda item: item['total_relations'], reverse=True)
    return sorted_results


def main():
    parser = argparse.ArgumentParser(description='Analyze Python ENRE reports for one-hop relationships.')
    parser.add_argument('input_file', help='Path to the ENRE JSON report file.')
    parser.add_argument('-o', '--output_file', default='python_analysis_report.json', help='Path to save the analysis output JSON file. Defaults to "python_analysis_report.json" in the current directory.')
    parser.add_argument('-q', '--qualified_name', help='Optional: The qualifiedName of a specific entity to analyze.')

    args = parser.parse_args()
    results = analyze_python_enre_report(args.input_file, args.qualified_name)

    if results:
        try:
            with open(args.output_file, 'w', encoding='utf-8') as f:
                json.dump(results, f, indent=4)
            print(f"Analysis complete. Results saved to '{os.path.abspath(args.output_file)}'")
        except IOError as e:
            print(f"Error writing to output file '{args.output_file}': {e}")


if __name__ == '__main__':
    main()
