'''
This script retrieves code snippets related to a specific entity's one-hop relationships,
based on reports generated by ENRE-C/C++ and cpp_utils/relation_analyzer.py.
'''
import json
import os
import argparse


def _normalize_report_data(raw: object) -> dict:
    if isinstance(raw, list) and raw and isinstance(raw[0], dict):
        return raw[0]
    if isinstance(raw, dict):
        return raw
    return {}


def _normalize_variables(raw_variables: object) -> list[dict]:
    if not isinstance(raw_variables, list):
        return []
    normalized: list[dict] = []
    for var in raw_variables:
        if not isinstance(var, dict):
            continue
        var_id = var.get('id')
        qname = var.get('qualifiedName')
        entity_type = var.get('entityType') or var.get('category')
        entity_file = var.get('entityFile') or var.get('File')
        start_line = var.get('startLine')
        end_line = var.get('endLine')
        start_col = var.get('startColumn')
        end_col = var.get('endColumn')
        parent_id = var.get('parentID')
        if parent_id is None:
            parent_id = var.get('parentId')
        location = {
            "startLine": start_line,
            "endLine": end_line,
            "startColumn": start_col,
            "endColumn": end_col,
        }
        normalized.append({
            "id": var_id,
            "qualifiedName": qname,
            "category": entity_type,
            "File": entity_file,
            "location": location,
            "parentId": parent_id,
        })
    return normalized


def _resolve_path(project_root: str, file_path: str | None) -> str:
    if not file_path:
        return ""
    if os.path.isabs(file_path):
        return file_path
    return os.path.join(project_root, file_path)


def get_code_snippet(file_path, start_line, end_line=None, context_lines=5):
    if not os.path.exists(file_path):
        return f"Error: Source file not found at {file_path}"

    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()
    except UnicodeDecodeError:
        print(f"Warning: Failed to decode '{file_path}' with UTF-8. Retrying with 'latin-1' encoding.")
        try:
            with open(file_path, 'r', encoding='latin-1') as f:
                lines = f.readlines()
        except Exception as e:
            print(f"Error reading file '{file_path}' with fallback encoding 'latin-1': {e}")
            return None
    except Exception as e:
        return f"Error reading file {file_path}: {e}"

    if not isinstance(start_line, int) or start_line <= 0:
        return None

    start_idx = start_line - 1
    if end_line is not None and isinstance(end_line, int) and end_line >= start_line:
        end_idx = min(end_line - 1, start_idx + context_lines - 1, len(lines) - 1)
    else:
        start_idx = max(0, start_line - 1 - context_lines)
        end_idx = min(len(lines) - 1, start_line - 1 + context_lines)

    snippet_lines = lines[start_idx : end_idx + 1]
    return "".join(snippet_lines)


def retrieve_code_context(entity_relations: dict, enre_report_path: str, project_root: str, output_path: str | None = None) -> dict | None:
    try:
        with open(enre_report_path, 'r', encoding='utf-8') as f:
            enre_data = json.load(f)
    except UnicodeDecodeError:
        print(f"Warning: Failed to decode '{enre_report_path}' with UTF-8. Retrying with 'latin-1' encoding.")
        try:
            with open(enre_report_path, 'r', encoding='latin-1') as f:
                enre_data = json.load(f)
        except Exception as e:
            print(f"Error reading file '{enre_report_path}' with fallback encoding 'latin-1': {e}")
            return None
    except (IOError, json.JSONDecodeError) as e:
        print(f"Error reading or parsing ENRE report '{enre_report_path}': {e}")
        return None

    enre_data = _normalize_report_data(enre_data)
    variables = _normalize_variables(enre_data.get('variables', []))
    enre_node_map = {var['qualifiedName']: var for var in variables if var.get('qualifiedName')}

    id_node_map = {var['id']: var for var in variables if 'id' in var}

    parent_id_to_functions_map = {}
    for var in variables:
        if var.get('category') == 'Function':
            parent_id = var.get('parentId')
            if parent_id is not None:
                parent_id_to_functions_map.setdefault(parent_id, []).append(var)

    category = entity_relations.get('category')

    if category == 'Function':
        for rel_key in ['calls', 'overrides']:
            if rel_key in entity_relations:
                for info in entity_relations[rel_key]:
                    target_qname = info.get('qualifiedName')
                    target_node = enre_node_map.get(target_qname)
                    if not target_node:
                        continue
                    file_path = _resolve_path(project_root, target_node.get('File'))
                    location = target_node.get('location') or {}
                    start_line = location.get('startLine')
                    end_line = location.get('endLine')
                    if start_line:
                        info['code_snippet'] = get_code_snippet(file_path, start_line, end_line=end_line, context_lines=5)
                        info['target_location'] = {'startLine': start_line, 'endLine': end_line}

        for rel_key in ['called_by', 'overridden_by']:
            if rel_key in entity_relations:
                for info in entity_relations[rel_key]:
                    file_path = _resolve_path(project_root, info.get('File'))
                    location = info.get('location', {}) or {}
                    start_line = location.get('startLine')
                    if start_line:
                        info['code_snippet'] = get_code_snippet(file_path, start_line, context_lines=5)

    if category in {'Class', 'Struct', 'Union', 'Template'}:
        for info in entity_relations.get('instantiated_in', []):
            file_path = _resolve_path(project_root, info.get('File'))
            start_line = info.get('startLine') or info.get('location', {}).get('startLine')
            if start_line:
                info['code_snippet'] = get_code_snippet(file_path, start_line, context_lines=5)

        for info in entity_relations.get('inherits_from', []):
            parent_id = info.get('id')
            methods = parent_id_to_functions_map.get(parent_id, [])
            info['contained_functions_snippets'] = []
            for fn in methods:
                fn_file_path = _resolve_path(project_root, fn.get('File'))
                fn_location = fn.get('location') or {}
                fn_start = fn_location.get('startLine')
                fn_end = fn_location.get('endLine')
                if fn_start:
                    snippet = get_code_snippet(fn_file_path, fn_start, end_line=fn_end, context_lines=3)
                    info['contained_functions_snippets'].append({
                        'qualifiedName': fn.get('qualifiedName'),
                        'code_snippet': snippet,
                    })

    if category == 'File':
        for info in entity_relations.get('includes', []):
            file_path = _resolve_path(project_root, entity_relations.get('File'))
            location = info.get('location', {}) or {}
            start_line = location.get('startLine')
            if start_line:
                info['code_snippet'] = get_code_snippet(file_path, start_line, context_lines=3)

        for info in entity_relations.get('defines', []):
            target_id = info.get('id')
            target_node = id_node_map.get(target_id)
            if not target_node:
                continue
            file_path = _resolve_path(project_root, target_node.get('File'))
            location = target_node.get('location') or {}
            start_line = location.get('startLine')
            end_line = location.get('endLine')
            if start_line:
                info['code_snippet'] = get_code_snippet(file_path, start_line, end_line=end_line, context_lines=3)

    if output_path:
        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                json.dump([entity_relations], f, indent=4)
            print(f"Code context retrieval complete. Results saved to '{os.path.abspath(output_path)}'")
        except IOError as e:
            print(f"Error writing to output file '{output_path}': {e}")

    return entity_relations


def main():
    parser = argparse.ArgumentParser(description='Retrieve code snippets for C/C++ entity relationships from ENRE reports.')
    parser.add_argument('--relation_report_file', required=True, help='Path to the JSON file containing the specific entity relationship report.')
    parser.add_argument('--enre_report_file', required=True, help='Path to the full ENRE-C/C++ JSON output file.')
    parser.add_argument('--project_root', required=True, help='The root directory of the analyzed C/C++ project.')
    parser.add_argument('--output_file', default='cpp_code_context_report.json', help='Path to save the output JSON file with code snippets.')

    args = parser.parse_args()

    try:
        with open(args.relation_report_file, 'r', encoding='utf-8') as f:
            relation_data = json.load(f)
        if not relation_data or not isinstance(relation_data, list):
            print("Error: Relation report is empty or not in the expected list format.")
            return
        entity_relations = relation_data[0]
    except (IOError, json.JSONDecodeError, IndexError) as e:
        print(f"Error reading or parsing relation report '{args.relation_report_file}': {e}")
        return

    retrieve_code_context(
        entity_relations=entity_relations,
        enre_report_path=args.enre_report_file,
        project_root=args.project_root,
        output_path=args.output_file
    )


if __name__ == '__main__':
    main()
