'''
This script analyzes a JSON report generated by ENRE-C/C++ to extract and summarize
one-hop relationships around core entities.
'''
import json
import os
import argparse
import re


def _normalize_report_data(raw: object) -> dict:
    if isinstance(raw, list) and raw and isinstance(raw[0], dict):
        return raw[0]
    if isinstance(raw, dict):
        return raw
    return {}


def _normalize_variables(raw_variables: object) -> list[dict]:
    if not isinstance(raw_variables, list):
        return []
    normalized: list[dict] = []
    for var in raw_variables:
        if not isinstance(var, dict):
            continue
        var_id = var.get('id')
        qname = var.get('qualifiedName')
        entity_type = var.get('entityType') or var.get('category')
        entity_file = var.get('entityFile') or var.get('File')
        start_line = var.get('startLine')
        end_line = var.get('endLine')
        start_col = var.get('startColumn')
        end_col = var.get('endColumn')
        parent_id = var.get('parentID')
        if parent_id is None:
            parent_id = var.get('parentId')
        location = {
            "startLine": start_line,
            "endLine": end_line,
            "startColumn": start_col,
            "endColumn": end_col,
        }
        normalized.append({
            "id": var_id,
            "qualifiedName": qname,
            "category": entity_type,
            "File": entity_file,
            "location": location,
            "parentId": parent_id,
        })
    return normalized


def _normalize_relations(raw_relations: object) -> list[dict]:
    if not isinstance(raw_relations, list):
        return []
    normalized: list[dict] = []
    for rel in raw_relations:
        if not isinstance(rel, dict):
            continue
        rel_type = rel.get('type')
        if rel_type is None and isinstance(rel.get('values'), dict):
            rel_type = rel['values'].get('kind')
        normalized.append({
            "type": rel_type,
            "src": rel.get('src'),
            "dest": rel.get('dest'),
            "location": rel.get('location') if isinstance(rel.get('location'), dict) else {},
        })
    return normalized


def _is_valid_location(loc: object) -> bool:
    if not isinstance(loc, dict):
        return False
    start_line = loc.get('startLine')
    return isinstance(start_line, int) and start_line > 0


def _coalesce_location(primary: object, fallback: object) -> dict:
    if _is_valid_location(primary):
        return primary  # type: ignore[return-value]
    if _is_valid_location(fallback):
        return fallback  # type: ignore[return-value]
    return {}


def _coalesce_file(primary: object, fallback: object) -> str:
    if isinstance(primary, str) and primary and primary != "null":
        return primary
    if isinstance(fallback, str) and fallback and fallback != "null":
        return fallback
    return "N/A"


def _find_first_match_location(file_path: str, pattern: re.Pattern[str]) -> dict:
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            for i, line in enumerate(f, start=1):
                m = pattern.search(line)
                if m:
                    col = m.start() + 1
                    return {"startLine": i, "endLine": i, "startColumn": col, "endColumn": col}
    except UnicodeDecodeError:
        try:
            with open(file_path, "r", encoding="latin-1") as f:
                for i, line in enumerate(f, start=1):
                    m = pattern.search(line)
                    if m:
                        col = m.start() + 1
                        return {"startLine": i, "endLine": i, "startColumn": col, "endColumn": col}
        except Exception:
            return {}
    except Exception:
        return {}
    return {}


def analyze_cpp_enre_report(report_path, target_qualified_name=None, enre_data=None):
    """
    Parses a C/C++ ENRE report to analyze one-hop relationships.
    Can be passed a file path or a pre-loaded data dictionary.

    Focused one-hop semantics:
    - Call: Function -> (Function/Template/Typedef/...) depending on report
    - Extend: inheritance among Class/Struct/Template
    - Instantiate (approx): Function -> (Class/Struct/Union/Template) via Use/Set/Modify

    Notes:
    - ENRE-C/C++ reports may contain many additional relations. This analyzer keeps
      the output compact and stable for downstream code-context retrieval.
    """
    if enre_data:
        data = enre_data
    elif report_path and os.path.exists(report_path):
        try:
            with open(report_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
        except UnicodeDecodeError:
            print(f"Warning: Failed to decode '{report_path}' with UTF-8. Retrying with 'latin-1' encoding.")
            try:
                with open(report_path, 'r', encoding='latin-1') as f:
                    data = json.load(f)
            except Exception as e:
                print(f"Error reading file '{report_path}' with fallback encoding 'latin-1': {e}")
                return None
        except json.JSONDecodeError as e:
            print(f"Error decoding JSON from '{report_path}': {e}")
            return None
    else:
        print(f"Error: Report file not found at '{report_path}' and no data provided.")
        return None

    data = _normalize_report_data(data)
    variables = _normalize_variables(data.get('variables', []))
    relations = _normalize_relations(data.get('relations', data.get('cells', [])))

    tracked_categories = {var.get('category') for var in variables if var.get('category')}

    node_map = {
        var['id']: var
        for var in variables
        if var.get('category') in tracked_categories and var.get('id') is not None
    }
    id_to_var = {var.get('id'): var for var in variables if var.get('id') is not None}

    type_like_categories = {'Class', 'Struct', 'Union', 'Template'}

    type_to_functions = {}
    for var in variables:
        if var.get('category') != 'Function':
            continue
        parent_id = var.get('parentId')
        if parent_id is None:
            continue
        type_to_functions.setdefault(parent_id, []).append({
            'id': var.get('id'),
            'qualifiedName': var.get('qualifiedName'),
            'location': var.get('location') or {},
            'File': var.get('File', 'N/A') or 'N/A',
        })

    instantiated_in = {}
    for rel in relations:
        src_id = rel.get('src')
        dest_id = rel.get('dest')
        rel_type = rel.get('type')
        if rel_type not in {'Use', 'Set', 'Modify'}:
            continue

        src_var = id_to_var.get(src_id, {})
        dest_var = id_to_var.get(dest_id, {})
        if src_var.get('category') != 'Function':
            continue
        if dest_var.get('category') not in type_like_categories:
            continue

        location = _coalesce_location(rel.get('location') or {}, src_var.get('location') or {})
        instantiated_in.setdefault(dest_id, []).append({
            'id': src_id,
            'qualifiedName': src_var.get('qualifiedName', 'N/A'),
            'File': src_var.get('File', 'N/A'),
            'location': location,
            'startLine': location.get('startLine'),
        })

    analysis_results = {}
    for node_id, node_info in node_map.items():
        category = node_info.get('category')
        result = {
            'id': node_id,
            'qualifiedName': node_info.get('qualifiedName', 'N/A'),
            'category': category,
            'File': node_info.get('File', 'N/A'),
        }

        if category == 'Function':
            result['calls'] = []
            result['called_by'] = []
            result['overrides'] = []
            result['overridden_by'] = []

        if category in type_like_categories:
            result['inherits_from'] = []
            result['subclasses'] = []
            result['instantiated_in'] = instantiated_in.get(node_id, [])
            result['contains_functions'] = type_to_functions.get(node_id, [])

        if category == 'File':
            result['includes'] = []
            result['included_by'] = []
            result['defines'] = []

        if category == 'Namespace':
            result['defines'] = []

        analysis_results[node_id] = result

    for rel in relations:
        src_id = rel.get('src')
        dest_id = rel.get('dest')
        rel_type = rel.get('type')
        raw_location = rel.get('location') or {}

        if src_id not in node_map or dest_id not in node_map:
            continue

        src_node_info = node_map[src_id]
        dest_node_info = node_map[dest_id]
        src_category = src_node_info.get('category')
        dest_category = dest_node_info.get('category')
        src_file = _coalesce_file(src_node_info.get('File'), None)
        dest_file = _coalesce_file(dest_node_info.get('File'), None)

        if rel_type == 'Call' and src_category == 'Function':
            location = _coalesce_location(raw_location, dest_node_info.get('location') or {})
            analysis_results[src_id]['calls'].append({
                'id': dest_id,
                'qualifiedName': dest_node_info.get('qualifiedName', 'N/A'),
                'category': dest_category,
                'File': dest_file,
                'location': location,
            })
            if dest_category == 'Function':
                called_by_location = _coalesce_location(raw_location, src_node_info.get('location') or {})
                analysis_results[dest_id]['called_by'].append({
                    'id': src_id,
                    'qualifiedName': src_node_info.get('qualifiedName', 'N/A'),
                    'File': src_file,
                    'location': called_by_location,
                })

        if rel_type == 'Extend' and src_category in type_like_categories and dest_category in type_like_categories:
            analysis_results[src_id]['inherits_from'].append({
                'id': dest_id,
                'qualifiedName': dest_node_info.get('qualifiedName', 'N/A'),
                'category': dest_category,
                'File': dest_node_info.get('File', 'N/A'),
            })
            analysis_results[dest_id]['subclasses'].append({
                'id': src_id,
                'qualifiedName': src_node_info.get('qualifiedName', 'N/A'),
                'category': src_category,
                'File': src_node_info.get('File', 'N/A'),
            })

        if rel_type == 'Override' and src_category == 'Function' and dest_category == 'Function':
            location = _coalesce_location(raw_location, dest_node_info.get('location') or {})
            analysis_results[src_id]['overrides'].append({
                'id': dest_id,
                'qualifiedName': dest_node_info.get('qualifiedName', 'N/A'),
                'File': dest_file,
                'location': location,
            })
            overridden_by_location = _coalesce_location(raw_location, src_node_info.get('location') or {})
            analysis_results[dest_id]['overridden_by'].append({
                'id': src_id,
                'qualifiedName': src_node_info.get('qualifiedName', 'N/A'),
                'File': src_file,
                'location': overridden_by_location,
            })

        if rel_type == 'Include' and src_category == 'File' and dest_category == 'File':
            location = _coalesce_location(raw_location, src_node_info.get('location') or {})
            if not _is_valid_location(location) and src_file != "N/A" and dest_file != "N/A":
                inc_name = os.path.basename(dest_file)
                location = _find_first_match_location(src_file, re.compile(rf'^\s*#\s*include\s*[<"]{re.escape(inc_name)}[>"]'))
            analysis_results[src_id]['includes'].append({
                'id': dest_id,
                'qualifiedName': dest_node_info.get('qualifiedName', 'N/A'),
                'File': dest_file,
                'location': location,
            })
            included_by_location = location
            analysis_results[dest_id]['included_by'].append({
                'id': src_id,
                'qualifiedName': src_node_info.get('qualifiedName', 'N/A'),
                'File': src_file,
                'location': included_by_location,
            })

        if rel_type == 'Define' and src_category in {'File', 'Namespace'}:
            location = _coalesce_location(raw_location, dest_node_info.get('location') or {})
            define_file = _coalesce_file(dest_node_info.get('File'), src_node_info.get('File'))
            if not _is_valid_location(location) and define_file != "N/A" and dest_category == "Namespace":
                ns_name = str(dest_node_info.get('qualifiedName') or '').split('::')[-1]
                if ns_name:
                    location = _find_first_match_location(define_file, re.compile(rf'\bnamespace\s+{re.escape(ns_name)}\b'))
            analysis_results[src_id]['defines'].append({
                'id': dest_id,
                'qualifiedName': dest_node_info.get('qualifiedName', 'N/A'),
                'category': dest_category,
                'File': define_file,
                'location': location,
            })

    if target_qualified_name:
        target_id = None
        for node_id, node_info in node_map.items():
            if node_info.get('qualifiedName') == target_qualified_name:
                target_id = node_id
                break
        if target_id and target_id in analysis_results:
            analysis_results = {target_id: analysis_results[target_id]}
            print(f"Found entity: {target_qualified_name}. Analyzing its relationships.")
        else:
            print(f"Warning: Entity with qualifiedName '{target_qualified_name}' not found in the report.")
            return []

    for result in analysis_results.values():
        if 'calls' in result:
            result['calls'] = sorted(result['calls'], key=lambda x: (x.get('qualifiedName', ''), x.get('location', {}).get('startLine', 0)))
        if 'called_by' in result:
            result['called_by'] = sorted(result['called_by'], key=lambda x: (x.get('qualifiedName', ''), x.get('location', {}).get('startLine', 0)))
        if 'overrides' in result:
            result['overrides'] = sorted(result['overrides'], key=lambda x: (x.get('qualifiedName', ''), x.get('location', {}).get('startLine', 0)))
        if 'overridden_by' in result:
            result['overridden_by'] = sorted(result['overridden_by'], key=lambda x: (x.get('qualifiedName', ''), x.get('location', {}).get('startLine', 0)))
        if 'inherits_from' in result:
            result['inherits_from'] = sorted(result['inherits_from'], key=lambda x: x.get('qualifiedName', ''))
        if 'subclasses' in result:
            result['subclasses'] = sorted(result['subclasses'], key=lambda x: x.get('qualifiedName', ''))
        if 'instantiated_in' in result:
            result['instantiated_in'] = sorted(result['instantiated_in'], key=lambda x: (x.get('File', ''), x.get('startLine', 0) or 0))
        if 'contains_functions' in result:
            result['contains_functions'] = sorted(result['contains_functions'], key=lambda x: x.get('location', {}).get('startLine', 0))
        if 'includes' in result:
            result['includes'] = sorted(result['includes'], key=lambda x: (x.get('qualifiedName', ''), x.get('location', {}).get('startLine', 0)))
        if 'included_by' in result:
            result['included_by'] = sorted(result['included_by'], key=lambda x: (x.get('qualifiedName', ''), x.get('location', {}).get('startLine', 0)))
        if 'defines' in result:
            result['defines'] = sorted(result['defines'], key=lambda x: (x.get('category', ''), x.get('qualifiedName', '')))

        relation_keys = [
            'calls',
            'called_by',
            'overrides',
            'overridden_by',
            'inherits_from',
            'subclasses',
            'instantiated_in',
            'includes',
            'included_by',
            'defines',
        ]
        result['total_relations'] = sum(len(result.get(key, [])) for key in relation_keys)

    final_results_list = list(analysis_results.values())
    sorted_results = sorted(final_results_list, key=lambda item: item.get('total_relations', 0), reverse=True)
    return sorted_results


def main():
    parser = argparse.ArgumentParser(description='Analyze C/C++ ENRE reports for one-hop relationships.')
    parser.add_argument('input_file', help='Path to the ENRE JSON report file.')
    parser.add_argument('-o', '--output_file', default='cpp_analysis_report.json', help='Path to save the analysis output JSON file.')
    parser.add_argument('-q', '--qualified_name', help='Optional: The qualifiedName of a specific entity to analyze.')

    args = parser.parse_args()
    results = analyze_cpp_enre_report(args.input_file, args.qualified_name)

    if results:
        try:
            with open(args.output_file, 'w', encoding='utf-8') as f:
                json.dump(results, f, indent=4)
            print(f"Analysis complete. Results saved to '{os.path.abspath(args.output_file)}'")
        except IOError as e:
            print(f"Error writing to output file '{args.output_file}': {e}")


if __name__ == '__main__':
    main()
